### ISSUE TITLE
Make this installable?

### ISSUE THREAD

**Issue by Dpananos** [dracula/dRacula#4]
Is there interest in wrapping this in an R package so that in can be installed via R?

**Comment by jrdnbradford** [comment]
I definitely have this planned, once I have some extra time. Stay tuned!

**Comment by jrdnbradford** [comment]
@Dpananos see PR #5. More updates to come, but this gets it started.

**Comment by jrdnbradford** [comment]
PR #5 makes this installable. Closing.
